//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_AssignSurvey
    {
        public int AS_ID { get; set; }
        public string AS_ProjectID { get; set; }
        public string AS_ProjectName { get; set; }
        public string AS_Customer { get; set; }
        public Nullable<bool> AS_ClientPM { get; set; }
        public Nullable<bool> AS_ClientPE { get; set; }
        public Nullable<bool> AS_HelpDeskPM { get; set; }
        public Nullable<bool> AS_HelpDeskPE { get; set; }
        public Nullable<bool> AS_PEPM { get; set; }
        public Nullable<bool> AS_PMPE { get; set; }
        public Nullable<bool> AS_SalePM { get; set; }
        public Nullable<System.DateTime> AS_AssignDate { get; set; }
        public Nullable<bool> As_Status { get; set; }
        public Nullable<int> AS_CreatedBY { get; set; }
        public Nullable<System.DateTime> AS_CreatedDate { get; set; }
        public Nullable<int> AS_UpdatedBy { get; set; }
        public Nullable<System.DateTime> AS_UpdatedDate { get; set; }
    }
}
