//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Login
    {
        public int L_ID { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string L_Name { get; set; }
        public string L_Password { get; set; }
        public Nullable<bool> L_Active { get; set; }
        public Nullable<int> L_CreatedBY { get; set; }
        public Nullable<System.DateTime> L_CreatedDate { get; set; }
        public Nullable<int> L_UpdatedBy { get; set; }
        public Nullable<System.DateTime> L_UpdatedDate { get; set; }
    }
}
