//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Project
    {
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Discription { get; set; }
        public Nullable<int> P_PM { get; set; }
        public Nullable<int> P_PE { get; set; }
        public Nullable<int> P_SalesPM { get; set; }
        public Nullable<int> P_HPM { get; set; }
        public Nullable<int> P_HPE { get; set; }
        public Nullable<bool> P_IsActive { get; set; }
        public Nullable<int> P_CreatedBY { get; set; }
        public Nullable<System.DateTime> P_CreatedDate { get; set; }
        public Nullable<int> P_UpdatedBy { get; set; }
        public Nullable<System.DateTime> P_UpdatedDate { get; set; }
    }
}
