//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Questionnaire
    {
        public int Q_ID { get; set; }
        public string Q_Type { get; set; }
        public Nullable<int> Q_QuestionSequence { get; set; }
        public string Q_Question { get; set; }
        public Nullable<bool> Q_Status { get; set; }
        public Nullable<int> Q_CreatedBY { get; set; }
        public Nullable<System.DateTime> Q_CreatedDate { get; set; }
        public Nullable<int> Q_UpdatedBy { get; set; }
        public Nullable<System.DateTime> Q_UpdatedDate { get; set; }
    }
}
