//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_Role
    {
        public int RO_ID { get; set; }
        public string RO_Name { get; set; }
        public string RO_Description { get; set; }
        public Nullable<bool> RO_IsActive { get; set; }
        public Nullable<int> RO_CreatedBY { get; set; }
        public Nullable<System.DateTime> RO_CreatedDate { get; set; }
        public Nullable<int> RO_UpdatedBy { get; set; }
        public Nullable<System.DateTime> RO_UpdatedDate { get; set; }
    }
}
