//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_SubmitSurvey
    {
        public int SS_ID { get; set; }
        public Nullable<int> SS_AS_ID { get; set; }
        public Nullable<int> SS_P_ID { get; set; }
        public Nullable<int> SS_U_ID { get; set; }
        public string SS_U_Role { get; set; }
        public Nullable<int> SS_Status { get; set; }
        public Nullable<bool> SS_IsActive { get; set; }
        public Nullable<int> SS_CreatedBY { get; set; }
        public Nullable<System.DateTime> SS_CreatedDate { get; set; }
        public Nullable<int> SS_UpdatedBy { get; set; }
        public Nullable<System.DateTime> SS_UpdatedDate { get; set; }
    }
}
