//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectSurveyEntities : DbContext
    {
        public ProjectSurveyEntities()
            : base("name=ProjectSurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AS_AssignSurvey> AS_AssignSurvey { get; set; }
        public DbSet<L_Login> L_Login { get; set; }
        public DbSet<P_Project> P_Project { get; set; }
        public DbSet<Q_Questionnaire> Q_Questionnaire { get; set; }
        public DbSet<RO_Role> RO_Role { get; set; }
        public DbSet<SS_SubmitSurvey> SS_SubmitSurvey { get; set; }
        public DbSet<U_User> U_User { get; set; }
    }
}
