//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.SurveyEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class U_User
    {
        public int U_ID { get; set; }
        public string U_FirstName { get; set; }
        public string U_LastName { get; set; }
        public string U_Email { get; set; }
        public string U_Mobile { get; set; }
        public string U_Role { get; set; }
        public Nullable<bool> U_Status { get; set; }
        public Nullable<int> U_CreatedBY { get; set; }
        public Nullable<System.DateTime> U_CreatedDate { get; set; }
        public Nullable<int> U_UpdatedBy { get; set; }
        public Nullable<System.DateTime> U_UpdatedDate { get; set; }
    }
}
